---
version: "2.1"
services:
  rdesktop:
    image: lscr.io/linuxserver/rdesktop:arm64v8-ubuntu-kde
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - /home/ubuntu/rdesktop:/config #optional
    ports:
      - 3389:3389
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "6gb" #optional
    restart: unless-stopped