user  nginx;
worker_processes  auto;

events {
  worker_connections  1024;
}

http {
  # Limite de taxa de requisições - Rate Limiting
  limit_req_zone $binary_remote_addr zone=mylimit:10m rate=550r/s;  # 550 requisições por segundo

  server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Expor os arquivos de validação do certbot
    location /.well-known/acme-challenge {
        allow all;
        root /var/www/certbot;
    }
  }
}
