user  nginx;
worker_processes  auto;

events {
  worker_connections  1024;
}

http {
  # Limite de taxa de requisições - Rate Limiting
  limit_req_zone $binary_remote_addr zone=mylimit:10m rate=550r/s;  # 550 requisições por segundo
  server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name meudominio.com.br;
    if ($host != meudominio.com.br) {
        return 444;
    }
    ssl_certificate /etc/letsencrypt/live/meudominio.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/meudominio.com.br/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    proxy_buffers 16 4k;
    proxy_buffer_size 2k;

    # Limite de taxa de requisições - Rate Limiting
    limit_req zone=mylimit burst=200 nodelay;  # Permite um salto instantâneo de até 200 requisições
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    location /ibmmq/console/ {
        proxy_pass https://ibm-mq:9443/ibmmq/console/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /ibmmq/rest/ {
        proxy_pass https://ibm-mq:9443/ibmmq/rest/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }    
  }

  server {
    listen 1414 ssl;
    listen 1514 ssl;
    listen 9257 ssl;
    listen [::]:1414 ssl;
    listen [::]:1514 ssl;
    listen [::]:9157 ssl;
    server_name $DOMAIN;
    ssl_certificate /etc/letsencrypt/live/meudominio.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/meudominio.com.br/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    proxy_buffers 16 4k;
    proxy_buffer_size 2k;

    # Limite de taxa de requisições - Rate Limiting
    limit_req zone=mylimit burst=200 nodelay;  # Permite um salto instantâneo de até 200 requisições
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    location / {
        proxy_pass https://ibm-mq:$server_port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
