user  nginx;
worker_processes  auto;

events {
  worker_connections  1024;
}

http { 
   # Optional: Rate Limiting
  limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;  # Move here
  server {
    listen 80;
    server_name SERVER-NAME;
    return 301 https://$host$request_uri; 
  }

  server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name SERVER-NAME;

    ssl_certificate /etc/nginx/certs/ca-bundle.pem; 
    ssl_certificate_key /etc/nginx/certs/ssl.key; 
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # gzip on;
    # gzip_types text/plain text/css application/javascript application/json;

    proxy_buffers 16 4k;
    proxy_buffer_size 2k;

    # Optional: Caching
    # proxy_cache_path /data/nginx/cache levels=1:2 keys_zone=my_cache:10m max_size=1g;
    # proxy_cache my_cache;

    # Optional: Rate Limiting
    limit_req zone=mylimit burst=20; 

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
  
    location /obsidian {
      proxy_pass https://obsidian:3303/;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  
    location / {
      #return 301 /obsidian; # Redirect to Obsidian
      proxy_pass http://obsidian:3300;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
