---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_PORT=3300
      - CUSTOM_HTTPS_PORT=3303
      - CUSTOM_USER=abc
      - PASSWORD=abc
      - TITLE=Obsidian
      - LC_ALL=pt_BR.UTF-8
      - TZ=America/Sao_Paulo
      - NO_DECOR=true
    volumes:
      - /home/ubuntu/obsidian:/config
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - obsidian-net
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "443:443" # Expose HTTPS port for SSL
    volumes:
      - /home/ubuntu/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/certs:/etc/nginx/certs:ro
    depends_on:
      - obsidian
    networks:
      - obsidian-net

networks:
  obsidian-net:
