# renew_before_expiry = 30 days
version = 3.1.0
archive_dir = /etc/letsencrypt/archive/meudominio.com.br
cert = /etc/letsencrypt/live/meudominio.com.br/cert.pem
privkey = /etc/letsencrypt/live/meudominio.com.br/privkey.pem
chain = /etc/letsencrypt/live/meudominio.com.br/chain.pem
fullchain = /etc/letsencrypt/live/meudominio.com.br/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 88548e7277ed8a5f429c0557e031777a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
meudominio.com.br = /var/www/certbot
